### ISSUE TITLE
Black Screen & Validation Errors

### ISSUE THREAD

**Issue by skanti** [yknishidate/single-file-vulkan-pathtracing#1]
Hi,
just wanted to let you know that I really appreciate your single-file app. It's very clean & minimalistic!

However, it gives a black screen along with a bunch of validation errors for me:

![image](https://user-images.githubusercontent.com/11197940/120179378-67ac4b80-c202-11eb-891c-ee65ff090b6f.png)

Have a look at the LunarG VulkanSDK `vkconfig` for inspection or perhaps `NVIDIA Nsight Graphics` to get rid of them

**Comment by yknishidate** [comment]
Thanks for opening this issue!
Can you tell me if the issue occurs **without C++ optimization**?

**Comment by yknishidate** [comment]
This problem has been fixed. https://github.com/nishidate-yuki/single-file-vulkan-pathtracing/commit/f8ff34a9a5986b305a73ab3f3890119190903137
